### ISSUE TITLE
[BUG] Login panel at /login has bug where form disappears when you click on the login buttons on left

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/RadioLogger#59]
I tried a fresh install of this project on a development VM.

Click the button to progress to the login from the page at root  or /

I see that the /login page if you go directly click on the button to login, the login form disappears and you have to click on the login button again to get the login form back again.

**Comment by gbowne1** [comment]
Any ideas @jzunigarce ?

**Comment by jzunigarce** [comment]
I've been a bit disconnected because I have a lot of work. With respect to the problem you mention, this happens because you manipulate the visibility of the container on two occasions, first in the tabs.js file you have a condition to detect that the tab was pressed, when it finds it, it eliminates the hidden class, that makes it display, without However in the login.js file you are calling the slideToggle method for the selected button(tabs) and this causes an embedded style(display: hide) to be added to it if the element does not currently have it inlined (although it does via the class that you add hide apparently the slideToggle function only searches if it has it in line). Here the easiest suggestion would be to put separate components (pages) for registration and login or delegate responsibility to one of the scripts for hiding or showing to avoid conflicts

**Comment by jzunigarce** [comment]
If you want you can add a break point to the tabs.js and login.js files to see how they behave

**Comment by gbowne1** [comment]
I figured you might be busy.

Ok, I didnt design the original login/register/reset page.. that was a prior community contribution from a previous iteration of the project.  I kept it becuase it was the only example of the few that were even remotely working let alone looked decent to use.

I tried various break points with not a lot of success finding the exact behavior or trapping the bug in VSCode.

I agree to make separate components.  And for delegating responsibility for all DOM events and event listeners to app.js or index.js

**Comment by jzunigarce** [comment]
It may sound repetitive, but it would be very helpful if we make the mockup of the app first, it would be faster to program it, I can even help you with the frontend, I understand why you say that it is previous work, but I detect several with duplicate functionalities, maybe if you don't have much urgency to finish the project, we could design a front with a more robust structure

**Comment by gbowne1** [comment]
Its fine. I will work on the frontend this week.

I have not had a great deal of time yet to pay attention to this and other projects yet due to work and other things.

I will have a great deal more time in the coming weeks to finish this project.

**Comment by gbowne1** [comment]
Closing this as going to completely refactor the login.html file
